import type {
  Achievement,
  Certification,
  Course,
  Education,
  Experience,
  Portfolio,
  Project,
  Skill,
} from "../types";

const profileId = "a0000000-0000-4000-8000-000000000001";

const experiences: Experience[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    role: "Public Relations Team Leader",
    organization: "IT Club",
    location: "Alexandria, Egypt",
    start_date: "2025-08-01",
    end_date: null,
    is_current: true,
    bullets: [
      "Led the public relations team",
      "Coordinated the club and external organizations",
      "Managed partnerships and promoted activities",
      "Grew student and tech-community engagement",
    ],
    sort_order: 0,
    visible: true,
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    role: "Instructor IOT",
    organization: "Children Technological University (CTU)",
    location: "Alexandria, Egypt",
    start_date: "2025-07-01",
    end_date: "2026-08-01",
    is_current: false,
    bullets: [
      "Presented educational content interactively",
      "Guided hands-on activities",
      "Built students' confidence",
    ],
    sort_order: 1,
    visible: true,
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    role: "Intern, Full Stack Web Development (PHP Laravel)",
    organization: "Information Technology Institute (ITI)",
    location: "Alexandria, Egypt",
    start_date: "2025-07-01",
    end_date: "2025-10-01",
    is_current: false,
    bullets: [
      "Refactored legacy PHP",
      "Built RESTful APIs with Laravel",
      "Worked on secure database design",
      "Deployed scalable apps with senior engineers",
      "Built UI with Vue.js and Tailwind",
    ],
    sort_order: 2,
    visible: true,
  },
  {
    id: "10000000-0000-4000-8000-000000000004",
    role: "Training, Linux Red Hat Administration (120 hr)",
    organization: "National Telecommunications Institute (NTI)",
    location: "Alexandria, Egypt",
    start_date: "2025-07-01",
    end_date: "2025-08-01",
    is_current: false,
    bullets: [
      "Storage: partitions and LVM",
      "File systems, ACLs, and SELinux",
      "Firewall, containers, and RHEL server setup",
      "User accounts and access control",
    ],
    sort_order: 3,
    visible: true,
  },
];

const education: Education[] = [
  {
    id: "20000000-0000-4000-8000-000000000001",
    degree: "Bachelor of Information Technology (Network & Software Development)",
    institution: "Borg Al-Arab Technological University (BATU)",
    start_date: "2024-09-01",
    end_date: "2028-01-01",
    details: "Current student.",
    sort_order: 0,
    visible: true,
  },
];

const projects: Project[] = [
  {
    id: "30000000-0000-4000-8000-000000000001",
    slug: "wali-el-ahd-hospital-management-system",
    title: "Wali El-Ahd Hospital Management System",
    kind: "software",
    brief:
      "Full system for an exclusive OB/GYN maternity hospital, with an API-first Laravel backend and a React web client.",
    description:
      "Full system for an exclusive OB/GYN maternity hospital. API-first Laravel backend, React web client, with future mobile and desktop clients. Online booking with queue numbers, pregnancy and delivery records, newborn and NICU files, lab, radiology, pharmacy and supplies inventory, itemized inpatient billing with e-invoices, and WhatsApp result delivery. Google login and Telegram integration are planned.",
    start_date: "2026-09-01",
    end_date: "2026-10-01",
    tech: ["Laravel", "React"],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: true,
    featured: true,
    sort_order: 0,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000002",
    slug: "the-knower-system",
    title: "The Knower System",
    kind: "software",
    brief:
      "Flagship management platform of The Knower OS agency, built with Laravel and React, including a Sales and Digital Marketing module.",
    description:
      "Flagship management platform of The Knower OS agency. Laravel and React, deployed on Render with MySQL on Aiven, and a custom domain. Includes a Sales and Digital Marketing module.",
    start_date: "2026-07-01",
    end_date: "2026-09-01",
    tech: ["Laravel", "React", "MySQL"],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: false,
    featured: true,
    sort_order: 1,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000003",
    slug: "teaching-management-system",
    title: "Teaching Management System",
    kind: "software",
    brief:
      "Platform for teachers to publish documents and videos in a copy-protected environment, with subscriptions and financial tracking.",
    description:
      "Platform for teachers to publish documents and videos in a copy-protected environment, with student subscriptions, WhatsApp notifications, and financial tracking.",
    start_date: "2026-08-01",
    end_date: "2026-09-01",
    tech: [],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: true,
    featured: false,
    sort_order: 2,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000004",
    slug: "katalog",
    title: "Katalog",
    kind: "software",
    brief: "Mobile app and digital legacy platform for continuous content delivery beyond a person's lifetime.",
    description:
      "Digital legacy platform for continuous content delivery beyond a person's lifetime. Built as a mobile app.",
    start_date: "2025-12-01",
    end_date: "2026-09-01",
    tech: [],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: false,
    featured: false,
    sort_order: 3,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000005",
    slug: "pharmacy-management-system",
    title: "Pharmacy Management System",
    kind: "software",
    brief:
      "Multi-branch pharmacy platform with a call-center flow for phone orders and a React mobile app.",
    description:
      "Multi-branch pharmacy platform with a call-center flow for phone orders and a React mobile app.",
    start_date: "2026-05-01",
    end_date: "2026-08-01",
    tech: ["React"],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: true,
    featured: false,
    sort_order: 4,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000006",
    slug: "smart-robotic-hand",
    title: "Smart robotic hand",
    kind: "hardware",
    brief:
      "Second-year graduation project: a wearable prototype with embedded control, motion, sensors, and wireless feedback.",
    description:
      "Second-year graduation project (Sep 2025–Jun 2026). Wearable prototype with embedded control, motion actuation, sensor integration, and wireless connectivity, with responsive movement and real-time feedback.",
    start_date: "2025-09-01",
    end_date: "2026-06-01",
    tech: ["Embedded systems"],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: false,
    featured: true,
    sort_order: 5,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000007",
    slug: "law-firm-management-system",
    title: "Law Firm Management System",
    kind: "software",
    brief:
      "Multi-platform system for law offices and clients, with a Laravel API, React clients, and a role and permission matrix.",
    description:
      "Multi-platform system for law offices and clients: Laravel API, React web, React mobile, and desktop apps, with a full ERD, a role and permission matrix, and a phased roadmap.",
    start_date: "2026-05-01",
    end_date: "2026-06-01",
    tech: ["Laravel", "React"],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: true,
    featured: false,
    sort_order: 6,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000008",
    slug: "infinity-crew",
    title: "Infinity Crew",
    kind: "software",
    brief: "Training platform for ICPC-style competitive programming preparation.",
    description:
      "ICPC and technical training platform for competitive programming preparation.",
    start_date: "2026-05-01",
    end_date: "2026-06-01",
    tech: [],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: false,
    featured: false,
    sort_order: 7,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000009",
    slug: "restaurant-cafe-ordering-system",
    title: "Restaurant / Café Ordering System",
    kind: "software",
    brief:
      "QR-based, multi-tenant ordering with realtime updates via Laravel Reverb, across multiple platforms.",
    description:
      "QR-based ordering, multi-tenant, with realtime updates via Laravel Reverb, built as a multi-platform system.",
    start_date: "2026-02-01",
    end_date: "2026-04-01",
    tech: ["Laravel", "Laravel Reverb"],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: true,
    featured: false,
    sort_order: 8,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000010",
    slug: "lms-school-management-system",
    title: "LMS School Management System",
    kind: "software",
    brief: "School management and learning platform with more than 30 database tables and four user roles.",
    description:
      "School management and learning platform, with more than 30 database tables and four user roles.",
    start_date: "2026-01-01",
    end_date: "2026-02-01",
    tech: [],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: true,
    featured: false,
    sort_order: 9,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000011",
    slug: "batu-project-management-system",
    title: "BATU Project Management System",
    kind: "software",
    brief: "Graduation-project management platform for students, supervisors, and admins.",
    description:
      "Graduation-project management platform for students, supervisors, and admins at BATU.",
    start_date: "2025-12-01",
    end_date: "2026-01-01",
    tech: [],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: true,
    featured: false,
    sort_order: 10,
    visible: true,
  },
  {
    id: "30000000-0000-4000-8000-000000000012",
    slug: "medical-robot",
    title: "Medical robot",
    kind: "hardware",
    brief:
      "First-year graduation project for preliminary diagnosis of infectious diseases, using temperature and heart-rate sensors.",
    description:
      "First-year graduation project. Preliminary diagnosis for infectious diseases, reducing doctor contact. Temperature and heart-rate sensors with remote data transmission. Skills used: Arduino, medical sensors, mechanical design, and teamwork.",
    start_date: null,
    end_date: null,
    tech: ["Arduino"],
    github_repo: null,
    live_url: null,
    cover_url: null,
    is_private: false,
    featured: false,
    sort_order: 11,
    visible: true,
  },
];

const skills: Skill[] = [
  ["Problem solving and critical thinking", "soft"],
  ["Team collaboration", "soft"],
  ["Communication and presentation", "soft"],
  ["Time management", "soft"],
  ["Authentication & Authorization", "technical"],
  ["Role-Based Access Control", "technical"],
  ["PHP Laravel", "technical"],
  ["Database Design", "technical"],
  ["Cloudflare", "tool"],
  ["Supabase", "tool"],
  ["PostgreSQL", "tool"],
  ["AWS", "tool"],
  ["Git", "tool"],
  ["Docker", "tool"],
  ["TypeScript", "tool"],
  ["React.js", "tool"],
  ["Python (AI)", "tool"],
  ["Web Development (HTML/CSS/JS)", "tool"],
  ["React Native", "tool"],
  ["Linux (Ubuntu, Red Hat)", "tool"],
  ["Networking concepts", "tool"],
  ["Embedded systems", "tool"],
  ["Arabic", "language"],
  ["English", "language"],
].map(([name, category], index) => ({
  id: `40000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
  name,
  category: category as Skill["category"],
  level: null,
  sort_order: index,
  visible: true,
}));

const certificationRows: [string, string | null][] = [
  ["Instructor CTU", "Children Technological University"],
  ["Arduino", "Borg Al-Arab Technological University"],
  ["Cybersecurity Level 1", "Skills Area"],
  ["Cloud Computing", "Creativa"],
  ["Mobile Application, React Native", null],
  ["AI Fundamentals", "Borg Al-Arab Technological University"],
  ["Front-End Development", "Borg Al-Arab Technological University"],
  ["HP Introductory Cybersecurity", "HP"],
  ["ITI Full Stack PHP", "Information Technology Institute"],
  ["Linux Red Hat Administration", "National Telecommunications Institute"],
];

const certifications: Certification[] = certificationRows.map(([title, issuer], index) => ({
  id: `50000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
  title,
  issuer,
  issued_on: null,
  credential_url: null,
  sort_order: index,
  visible: true,
}));

const courses: Course[] = [
  {
    id: "60000000-0000-4000-8000-000000000001",
    title: "CCNA Level 1",
    provider: "Cisco Networking Academy",
    start_date: "2026-09-01",
    end_date: null,
    status: "in_progress",
    description: null,
    sort_order: 0,
    visible: true,
  },
  {
    id: "60000000-0000-4000-8000-000000000002",
    title: "Mobile Application (React Native)",
    provider: null,
    start_date: "2026-02-01",
    end_date: "2026-04-01",
    status: "completed",
    description: null,
    sort_order: 1,
    visible: true,
  },
  {
    id: "60000000-0000-4000-8000-000000000003",
    title: "Front-End Development",
    provider: null,
    start_date: "2025-03-01",
    end_date: "2025-05-01",
    status: "completed",
    description: null,
    sort_order: 2,
    visible: true,
  },
  {
    id: "60000000-0000-4000-8000-000000000004",
    title: "AI Development",
    provider: null,
    start_date: "2025-03-01",
    end_date: "2025-05-01",
    status: "completed",
    description: "Python, Pandas, and Jupyter.",
    sort_order: 3,
    visible: true,
  },
];

const achievements: Achievement[] = [
  {
    id: "70000000-0000-4000-8000-000000000001",
    title: "Ranked 7th among BATU teams",
    event: "ECPC 2026, Collegiate Programming Competition",
    achieved_on: "2026-08-01",
    details: null,
    sort_order: 0,
    visible: true,
  },
];

export function seedPortfolio(): Portfolio {
  return {
    profile: {
      id: profileId,
      full_name: "Omar Mehawed",
      title: "IT Developer",
      summary:
        "Detail-oriented IT student at Borg Al-Arab Technological University (2024–2028), with a versatile background in full-stack development, system administration, and technical instruction. Skilled in PHP, React, and cloud technologies; builds scalable solutions, manages complex systems, and communicates clearly with diverse teams. Founder of The Knower OS, a freelance software agency, and OppStore, a clothing brand.",
      location: "Sidi-Beshr, Alexandria, Egypt",
      photo_url: null,
      cover_url: null,
      cv_public_url: null,
      updated_at: null,
    },
    socialLinks: [],
    experiences,
    education,
    projects,
    skills,
    certifications,
    courses,
    achievements,
  };
}

export const emptyContactSeed = {
  email: null as string | null,
  phone: null as string | null,
  show_phone: false,
};
